### ISSUE TITLE
Atom Keep consume internet usage 

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [lee-dohm/bug-report#49]
Atom Keep consume internet usage . I have tried with re-installing my previous download and update all the plugins up-to date. yet it's still consuming internet usage.

**Comment by lee-dohm** [comment]
You can report bugs for Atom at https://github.com/atom/atom/issues. This repository is for an add on package for Atom.

One thing to check is that Atom has a couple built-in packages: [metrics](https://github.com/atom/metrics) and [exception-reporting](https://github.com/atom/exception-reporting); that report certain activities to GitHub. You may want to disable them if you want Atom to not consume *any* Internet.
