### ISSUE TITLE
Opening jQuery-ui.min.js (big file) cause editor freeze and hang

### ISSUE THREAD

**Issue by yihaa5** [lee-dohm/bug-report#51]
Hi Guys,
Not sure if anyone having this issue. I tried to open a jquery-ui.min.js file in the editor. It loaded and hang for like 30++ seconds before i can start editing the file.

**Comment by lee-dohm** [comment]
This repository is for the bug-report Atom package. I suspect you're trying to report a bug on Atom itself? For that you should open an Issue on https://github.com/atom/atom.

Let me know if my understanding is incorrect.
