### ISSUE TITLE
atom editor freezes and has to be force quit when we try to edit a file requiring admin permissions

### ISSUE THREAD

**Issue by Anubhav410** [lee-dohm/bug-report#52]
OS : Mac

**Comment by Anubhav410** [comment]
I had submitted a very similar issue last week,  in which the editor was not freezing but the cursor used to stop showing.

**Comment by lee-dohm** [comment]
If you're trying to report an issue with Atom the editor, you can report it at https://github.com/atom/atom. This repository is for the [bug-report Atom package](https://atom.io/packages/bug-report).
