### ISSUE TITLE
File Side Bar Adjustment

### ISSUE THREAD

**Issue by laynef** [lee-dohm/bug-report#53]
Issue: 
When adjusting the side bar it does not reset to the desired position. Instead it continues adjusting until you quit the app.

Steps to Reproduce:
1. Install nuclide
2. Open Atom
3 Adjust the side bar
4. Try to set the position then continue coding
(It doesn't stop adjusting)

I'm trying to set the position and click the coding window

![untitled](https://cloud.githubusercontent.com/assets/14255968/17454966/44582574-5b5e-11e6-9dfa-2695c87b6faf.gif)

Versions:
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.9.1

Atom    : 1.9.5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

nuclide: v0.159.0

MacBook Pro
OSX El Capitan: version 10.11.6

**\* I can't tell if this is just a bug or if there is a specific command to use to stop adjusting and set the sidebar in place ***

**Comment by lee-dohm** [comment]
This sounds like you're trying to report a problem that you encountered using [Atom](https://atom.io). If you're having problems with Atom, you can use [Discuss, the official Atom and Electron message board](https://discuss.atom.io) to get support.

This repository is for the bug-report Atom package.
