### ISSUE TITLE
C or C++ Bug While using include.

### ISSUE THREAD

**Issue by Ehsan1997** [lee-dohm/bug-report#54]
When I type (#inc) and press enter for auto-complete, The editor types in (##include ".h" or ##include <.h>) instead of (#include ...).
Hope you will fix this soon..

**Comment by lee-dohm** [comment]
@Ehsan1997 This is the repository for my [bug-report package](https://atom.io/packages/bug-report). It doesn't have anything to do with auto-complete, C or C++.

If you're trying to report an Issue for Atom, you should go to https://github.com/atom/atom/issues to report it. You should also follow the instructions in the [Atom CONTRIBUTING guide on reporting bugs](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs).

Let me know if I've misunderstood your report and I can reopen the Issue.
