### ISSUE TITLE
Atom crashes on startup if Git Repository has a slash in filename (Windows)

### ISSUE THREAD

**Issue by hammadkhan** [lee-dohm/bug-report#55]
1. Create a git repository on mac
2. Add a file name test\temp.txt and commit.
3. Fetch this repository on Windows machine
4. Each time you open the repository in Atom (On Windows), Atom will crash. Other Git repositories will be opened fine.

Remove the test\temp.txt file on mac and push. hard reset the repository on windows and now the problem goes away. The issue is \ name in file name cause ATOM to crash.

**Comment by lee-dohm** [comment]
This isn't a location to report bugs for Atom. This is the repository for my [Atom package named bug-report](https://atom.io/packages/bug-report). You should report your Issue to https://github.com/atom/atom.
