### ISSUE TITLE
Holding CMD+W yields dozens of "do you want to save this file" popups?

### ISSUE THREAD

**Issue by ghost** [lee-dohm/bug-report#59]
I often just hold CMD+W to close all the tabs I have open.  If I have an unsaved file this causes an issue: I get a popup prompting me to save the popup that repeats dozens of times (as CMD+W triggered dozens of times on that file).

I should only see one popup and all the pending close requests should be ignored.

**Comment by lee-dohm** [comment]
This sounds like you're trying to report a problem that you encountered using [Atom](https://atom.io). If you're having problems with Atom, you can use [Discuss, the official Atom and Electron message board](https://discuss.atom.io) to get support.

This repository is for the bug-report Atom package.
