### ISSUE TITLE
Atom broken on Ubuntu 16

### ISSUE THREAD

**Issue by unclenachoduh** [lee-dohm/bug-report#60]
Atom starts up but is not functional at all. I tried uninstall and reinstall and same error persists

**Comment by lee-dohm** [comment]
This sounds like you're trying to report a problem that you encountered using [Atom](https://atom.io). If you're having problems with Atom, you can use [Discuss, the official Atom and Electron message board](https://discuss.atom.io) to get support.

This repository is for the bug-report Atom package.
