### ISSUE TITLE
Open batch file atom issue

### ISSUE THREAD

**Issue by rgupta114** [lee-dohm/bug-report#62]
Any batch file with extension .bat doesn't open in atom editor. Actions like double click on the .bat file in tree view runs the file and even file dragging & dropping on editor area doesn't seem to work.

**Comment by lee-dohm** [comment]
This repo is for the Atom package named [bug-report](https://atom.io/packages/bug-report), not for reporting bugs in Atom. If you're having a problem with Atom, please check out [Atom's support resources](https://github.com/atom/atom/blob/master/SUPPORT.md).
