### ISSUE TITLE
blank screen on open, does not respond to any commands

### ISSUE THREAD

**Issue by itsjacobhere** [lee-dohm/bug-report#63]
![atom_error](https://user-images.githubusercontent.com/34584341/34186587-89d8e7b0-e4e1-11e7-8401-dd01d46f08eb.PNG)

![atomeerr](https://user-images.githubusercontent.com/34584341/34186595-96fd44ae-e4e1-11e7-9b3b-385682ac8e64.PNG)

I have reinstalled atom multiple times and it opens like this every time, i opend the dev tools and get this error, i am on the newest version of atom.

What is the fix for this?

**Comment by lee-dohm** [comment]
This repo is for the Atom package named [bug-report](https://atom.io/packages/bug-report), not for reporting bugs in Atom. If you're having a problem with Atom, please check out [Atom's support resources](https://github.com/atom/atom/blob/master/SUPPORT.md).
