### ISSUE TITLE
Ctrl + TAB should lock all others functionalities

### ISSUE THREAD

**Issue by pir2open** [lee-dohm/bug-report#64]
Severity : Medium

When entering Ctrl+Tab mode (to switch between documents) a vertical tab is presented. So it feels like we can use down and up arrows (instead of tab and shift tab) to select the document we want, instead it modifies the current document by changing lines order.

I think document switcher should disable other functionalities (you don't copy/paste for example during doc switching, you copy before and paste after but never during)

**Comment by lee-dohm** [comment]
This repo is for the Atom package named [bug-report](https://atom.io/packages/bug-report), not for reporting bugs in Atom. If you're having a problem with Atom, please check out [Atom's support resources](https://github.com/atom/atom/blob/master/SUPPORT.md).
